version: '3.8'
services:
  php-apache-environment:
    container_name: php
    image: php:8.0-apache
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: TP
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '9906:3306'
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
